name: CI

on:
  push:
    branches:
      - main # или любая другая ветка, которую вы используете

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # или версия Node.js, которую вы используете

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test # предполагается, что у вас есть скрипт тестов в package.json

      - name: Build project
        run: npm run build
